### ISSUE TITLE
Different model or commands 

### ISSUE THREAD

**Issue by simplehima** [buzzibaer/FanPlugin.Wrapper#1]
i have a fan similar to yours and it uses the same IP but any command i run using through the FanPlugin it says command successful but nothing happens 
the app that came with the looks like this 
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/50a88859-970d-49a2-812a-7eb18fc8696b)

is there a way to capture or extract the commands for this app or what am i missing

**Comment by buzzibaer** [comment]
Hi did you try to use the TestApp?
https://github.com/buzzibaer/FanPlugin.Test
Maybe this produces more output.

I reverse engeneered the Original App via JAD + WireShark.
If you see "command successfull" there should be a valid response from the fan.

Tool is a littele bit picky with the Filenames.
See > https://github.com/buzzibaer/FanPlugin.Wrapper#how-to-sort-my-files-on-the-sd-card--problems-with-selection-of-file-ids

What kind of Fan are you using? 
Do you have a link to the product?
Your screenshot looks exactly like mine and should produce the same commands.

And do not forget, if you have ethernet or internet uplink in your cab, there some kind of gateway fuckup.
I know setting it out is a little bit complicated, but if it works, it is fun :)

But my first best guess wold be a filename fuckup... if it says "command successfull" it looks like everything is configured well.

**Comment by simplehima** [comment]
when i click turn off as u can see it is successful
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/70299d2b-0dba-4ae1-bf07-45fdf4c651e1)
This should play previous Video
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/c3da5e94-70be-4fc3-9af4-e16afe2f71cb)
but the fan does nothing

The Get file List crash the app
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/df8b5e91-ac71-4217-9982-1fb7ad998572)

I dont know but i am unable to find it online again maybe its out of stock but here are some photos about my fan
also the wifi name is 3D-388
![WhatsApp Image 2023-11-23 at 19 10 00_998febc6](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/251386a1-1062-446b-acf4-9b4f627d497c)
![WhatsApp Image 2023-11-23 at 19 10 00_93ae1404](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/4ca0e3ba-c99c-4596-b943-4668bcd462b0)
![WhatsApp Image 2023-11-23 at 19 10 00_ba86bf2f](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/026534bc-2b51-4c49-90f7-c0f134148dae)

Some Tsesting i made i tested with the original app to make sure that the connection between the pc and fan is established and working then i tried the TestApp and it says command successful but nothing happens to the fan happy to provide any additional information  

Maybe each model has a Different like payload ?

here are the files provided with my fan
https://drive.google.com/file/d/1MSKziH6n-Euef73wm0HACweYqcvOBGu4/view?usp=sharing

here are a screenshot of the pause command from original app
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/1b35d205-63a3-4a5b-bdd4-b51b1de34cb4)

**Comment by buzzibaer** [comment]
Hm...maybe Version update?

I will check my Fan with your App to check for the difference.

Is there also a Android App available for your Fan?
APK? Helps a lot / easier to analyse.

First impression:
Only the EXE is different

![2023-11-24 09_14_39-3Ds-Player V1 4](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/11458085/ccddd730-f6d7-4632-8740-b94ae115443b)

**Comment by simplehima** [comment]
Here is the apk that came with the fan
https://drive.google.com/file/d/1aM-uhfpu-_QgTCZXOoC3rN3LP4VndXox/view?usp=sharing
let me know if you need anything i can help you with.

**Comment by simplehima** [comment]
> Hm...maybe Version update?
> 
> I will check my Fan with your App to check for the difference.
> 
> Is there also a Android App available for your Fan? APK? Helps a lot / easier to analyse.
> 
> First impression: Only the EXE is different
> 
> ![2023-11-24 09_14_39-3Ds-Player V1 4](https://user-images.githubusercontent.com/11458085/285397952-ccddd730-f6d7-4632-8740-b94ae115443b.png)


Here is the apk that came with the fan
https://drive.google.com/file/d/1aM-uhfpu-_QgTCZXOoC3rN3LP4VndXox/view?usp=sharing
let me know if you need anything i can help you with.

**Comment by buzzibaer** [comment]
First investigation results:
My Fan == Version 3
Your Fan == Version 2

Slightly different command stack.

I will build a Version for you for testing.....

See:

![2023-11-24 14_59_21-buzzibaer_FanPlugin Wrapper_ 3d holografic fan for virtual pinball – Mozilla Fir](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/11458085/3a6afe3f-c71c-4a79-8c87-88c6972554c3)

**Comment by simplehima** [comment]
> First investigation results: My Fan == Version 3 Your Fan == Version 2
> 
> Slightly different command stack.
> 
> I will build a Version for you for testing.....
> 
> See:
> 
> ![2023-11-24 14_59_21-buzzibaer_FanPlugin Wrapper_ 3d holographic fan for virtual pinball – Mozilla Fir](https://user-images.githubusercontent.com/11458085/285476008-3a6afe3f-c71c-4a79-8c87-88c6972554c3.png)

i am so thankful, i will be pleased if you also shared the commands with me too i am working to make the fan interactive using ai and camera and your app will help me a lot

**Comment by buzzibaer** [comment]
i implemented your Version 2 Fan "dry".

Can you test it?
See >> https://github.com/buzzibaer/FanPlugin.Test/releases/tag/release_1.1.5

Button PowerUp and PowerDown do not work due to missing commands in your version.

If it works, i will give you the complete command set.

**Comment by simplehima** [comment]
> i implemented your Version 2 Fan "dry".
> 
> Can you test it? See >> https://github.com/buzzibaer/FanPlugin.Test/releases/tag/release_1.1.5
> 
> Button PowerUp and PowerDown do not work due to missing commands in your version.
> 
> If it works, i will give you the complete command set.

i am facing a connection problem 
but the older verstion 1.14 works fine (connection part)

last video command works
![image](https://github.com/buzzibaer/FanPlugin.Wrapper/assets/54166348/817c22f7-8a61-4ade-9223-e1d804c194e4)

**Comment by simplehima** [comment]
> > i implemented your Version 2 Fan "dry".
> > Can you test it? See >> https://github.com/buzzibaer/FanPlugin.Test/releases/tag/release_1.1.5
> > Button PowerUp and PowerDown do not work due to missing commands in your version.
> > If it works, i will give you the complete command set.
> 
> i am facing a connection problem but the older verstion 1.14 works fine (connection part)
> 
> last video command works ![image](https://user-images.githubusercontent.com/54166348/285499849-817c22f7-8a61-4ade-9223-e1d804c194e4.png)

Update i tested on a laptop to resolve the connectivity issues (usb adapter or windows 11 related problem)
so 
list of working commands
1. Set video works
2. Get list
3. Play last
4. play old
5. Loop
6. Stop loop

play old file does nothing 
as you mentioned power on / off not working

**Comment by buzzibaer** [comment]
Yes, the "play old file" was kind of experimental and is not working right :)

But if the rest works now for, i am happy :)

How do we proceed with the rest of the commands?

**Comment by simplehima** [comment]
> Yes, the "play old file" was kind of experimental and is not working right :)
> 
> But if the rest works now for, i am happy :)
> 
> How do we proceed with the rest of the commands?

about the rest of the command the fan came with a remote that turns off and on the fan using RF signal i can replicate this with an arduino nano and rf transmitter for the on and off (mainly it will be used for safety measures with sensors )
currently i will work with the 6 working commands and i really do appreciate your efforts and support i will also update you with my progress ❤️
i will be very thankful if you shared the code for v15

**Comment by buzzibaer** [comment]
New implementation for your Fan Version 2 
See > https://github.com/buzzibaer/FanPlugin.Wrapper/blob/main/Fan.cs

**Comment by simplehima** [comment]
> New implementation for your Fan Version 2 See > https://github.com/buzzibaer/FanPlugin.Wrapper/blob/main/Fan.cs

Thank you so much ❤️

**Comment by buzzibaer** [comment]
Test App for both Versions of the fan can now be found within the Test App.
See >> https://github.com/buzzibaer/FanPlugin.Test/releases/tag/release_1.2.0

**Comment by simplehima** [comment]
i started working on the project i was wondering do you have the function that encode and uploads to the fan

**Comment by buzzibaer** [comment]
Yes, i have it.
How do we share the code?

Propolal: I will add them to a new repo.

I can also contribute to your repo if you are going to add me.

But i am on vacation till sunday😉

**Comment by simplehima** [comment]
alright i will add you i am still working on the GUI and adding base Features "Invitation sent"
wish you a happy holiday
